"""create noise readings table

Revision ID: bb69425e2eb2
Revises: fff4bb140a60
Create Date: 2026-09-03 17:53:11.264161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb69425e2eb2'
down_revision: Union[str, Sequence[str], None] = 'fff4bb140a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noise_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('noise_level', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noise_readings_id'), 'noise_readings', ['id'], unique=False)
    op.create_index(op.f('ix_noise_readings_recorded_at'), 'noise_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_noise_readings_sensor_id'), 'noise_readings', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noise_readings_sensor_id'), table_name='noise_readings')
    op.drop_index(op.f('ix_noise_readings_recorded_at'), table_name='noise_readings')
    op.drop_index(op.f('ix_noise_readings_id'), table_name='noise_readings')
    op.drop_table('noise_readings')
    # ### end Alembic commands ###
